version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always

    environment:
      TZ: 'America/Sao_Paulo' # Put your own timezone here.
      WEBPASSWORD: 'piholeadmin' # Put a strong password here.
    
    # We'll use host networking simply because it is way easier to setup.
    network_mode: host
    
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    
    # Required for the DHCP server
    cap_add:
      - NET_ADMIN

    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 128M
            reservations:
              cpus: 0.25
              memory: 128M